project_id = "ofwuunclinnihtxjsaup"

[functions.generate-meal-plan]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.send-coach-reminder]
verify_jwt = false
